steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/ultimatetictactoepro-group13/lab-utttpr:$COMMIT_SHA', '.' ]
 # Push the container image to Artifact Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/ultimatetictactoepro-group13/lab-utttpr:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'lab-utttp'
   - '--image'
   - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/ultimatetictactoepro-group13/lab-utttpr:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--allow-unauthenticated'
   - '--platform'
   - 'managed'
   - '--port'
   - '8100'
images:
 - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/ultimatetictactoepro-group13/lab-utttpr'


substitutions:
  _PROJECT_ID: 'ultimate-ttt-pro-group-13'


